### ISSUE TITLE
Bulk check in errors

### ISSUE THREAD

**Issue by agates62** [bricelabelle/snipe-it-bulkedit#2]
I got bulk checkout to work but now bulk checkin isn't. I tried replicating what I did for the other, but no uck.

**Comment by Chaste-brigand** [comment]
Hi, have you by any chance succeeded in making the script work?
Bulk update is fine for me (thank you @bricelabelle ) but checkin and checkout don't seem to work in my case.

**Comment by bricelabelle** [comment]
Hi @Chaste-brigand, can you be more specific as to what is not working? Have you created an Errors tab in your sheet and checked that for any information? Do the status labels on the html files match the labels in your environment? In the script files on the Inventory.gs script, there are test functions for testCheckInAsset() and testCheckoutAsset() that you enter the asset id and the location id you want to check in/out to. You can find the asset id in the url in your browser when you are on the asset details page, and same for the location. Enter those in and run the test function and see what happens. It may be that the script simply needs more permissions or there is something specific to what's required at checkin in your environment.

**Comment by Chaste-brigand** [comment]
Hi @bricelabelle, 

Yes, I made sure to match the status labels on the html files with the ones I use on Snipe-IT. So, I did run the testCheckInAsset() and testCheckoutAsset(), both were not working and raised the following error:

TypeError: Cannot read property 'clear' of null

Turns out what posed a problem are the following lines, both present in the CheckInAsset and CheckOutAsset functions:

var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Errors")
      sheet.clear()

Apparently _sheet_ is not defined, which is weird. I just removed these lines and now the code works but it is just getting around the problem, not really solving it.

**Comment by bricelabelle** [comment]
It sounds like you probably didn't create another sheet/tab within your spreadsheet called "Errors". That sheet gets errors written to it and clears them each time you run the script which is what that code you removed is trying to do. I seem to have left that instruction out of the readme. I've updated it now to include that step during setup.

**Comment by tom-levp** [comment]
I thought about that today! I'll add back the lines. I also integrated additional instructions and everything works great, thanks again.

**Comment by bricelabelle** [comment]
Glad it's working now!
